[project]
name = "one_sent_per_line"
authors = [ {name = "José João Almeida", email = "jj@di.uminho.pt"} ]
license = {text = "MIT"}
version = "0.0.2"
description = "Reformat it in One Sentence per line"
dependencies = [ "jjcli"]

[project.scripts]
onesentpl = "one_sent_per_line:main"
